function uicontrolNames = assignUIControlNames(~)
%ASSIGNFOREGROUNDNAMES Creates uicontrol names of GUI.
%   
%   See also GETFOREGROUNDNAMES, FLUORODICOM_GUI.
%=========================================================================]

% Initialize output as a cell corresponding to the GUI's foregrounds.
uicontrolNames	= cell(4,1);

% Axis foreground names.
%%% None as of 2/15/19.

% Load foreground names.
loadUIControl	= {'loadDirectory';...
    'selectedDirectory';...
    'plotFile';...
    'fileList'};
uicontrolNames{2}	= [loadUIControl];
    
% Procedure foreground names.
procedureUIControl	= {'procedures'};
saveDataUIControl	= {'saveData'};
DHSUIControl	= {'wireWidth';...
    'leftOrRight';...
    'femoralHead';...
    'femoralNeck';...
    'wireSlope';...
    'TAD'};
PSHFUIControl	= {};
watchSurgeryUIControl	= {'pauseDuration';...
    'imageContrast';...
    'iterateImages'};
uicontrolNames{3}	= [procedureUIControl;...
    saveDataUIControl;...
    DHSUIControl;...
    PSHFUIControl;...
    watchSurgeryUIControl];

% Log foreground names.
%%% None as of 2/15/19.

