function fh = buildAxisForegroundPanel( fh )
%BUILDAXISFOREGROUNDPANEL Import main axis panel and its contents.
%   fh = BUILDAXISFOREGROUNDPANEL(fh) returns an updated figure handle
%   fh containing a panel for the main axis.
%   
%   See also MAIN>OPENINGFCN.
%==========================================================================

% Get color scheme.
global bgColor

% Build GUI Parts.
axisUICNames    = {'Axis Foreground'};
axisForegroundParent	= uipanel(...
    'Tag', axisUICNames{1}, 'Title', [], ...
    'Parent', fh, ...
    'BackgroundColor', bgColor, 'ForegroundColor', 'k', 'ShadowColor', [0 0 0], ...
    'Position', [.015 .025 .67 .95]);
[~]	= axes('Tag', 'Main Axis', 'Title', [], ...
    'Parent', axisForegroundParent, ...
    'XTick', [], ...
    'YTick', [], ...
    'Units', 'normalized', ...
    'Position', [.025 .025 .95 .95], ...
    'visible', 'off');

% Update fh UserData.
fh.set( 'UserData', fh.get( 'UserData' ).createNew( axisForegroundParent ) );

