function fh = buildMenu(fh)
%BUILDMENU Build menu of gui.
%   
%   See also MAIN, BUILDTOOLBAR, LOGINUSER_CALLBACK.
%==========================================================================

% Initialize menu bar.
m   = uimenu(fh);
mLoad   = uimenu(m, 'Text', 'Load', 'Tag', 'Load',...
    'Accelerator', 'l',...
    'Separator', 'On',...
    'Checked', 'Off',...
    'Interruptible', 'On',...
    'Visible', 'On',...
    'Enable', 'On',...
    'UserData', [])
mLoadDir    = uimenu(mLoad, 'Text' ,'Load Directory',...
    'Tag', 'LoadDirectory',...
    'Interruptible' ,'On');

mLogin	= uimenu(m, 'Text', 'Login',...
    'Tag', 'Login',...
    'Checked', 'On',...
    'Interruptible', 'Off',...
    'MenuSelectedFcn', {@loginUser_callback, fh})

%     'text', 'Surgery')

% Create button for user logging in (so results file knows the analyst).
[img, map]	= imread('login_logo.png');
img	= imresize(img, [16 16]);
[~]	= uipushtool('Tag', 'Login',...
    'ToolTipString', 'User Login',...
    'Parent', tb,...
    'Separator', 'on',...
    'CData', ind2rgb(img, map),...
    'ClickedCallback', {@loginUser_Callback, fh});
end