function out = basicStats( vector )
vector = vector( : );
[h, p] = ttest( vector );
if isnan( h )
    out = NaN( 7, 1 );
    return
end
out = vertcat( nanmedian( vector ),...
    nanmean( vector ),...
    nanstd( vector ),...
    nanmin( vector ),...
    nanmax( vector ),...
    h,...
    round( p, 4 ) );

