function out = basic_stats( vector )
vector = vector( : );
[h, p] = ttest( vector );
out = vertcat( median( vector ),...
    mean( vector ),...
    std( vector ),...
    min( vector ),...
    max( vector ),...
    h,...
    p );

